"""Returns Intelligence Foundation (Phase 5A).

Provides deterministic, explainable customer returns intelligence:
- Unit, order, and revenue return rate analytics
- Multi-dimensional profiling: SKU, Channel, Warehouse, SKU×Channel, SKU×Warehouse
- Return reason distributions and time series trends
- Data quality audits, sample size guards, and descriptive investigation flags
"""

from commerce_ai.returns.schemas import (
    InvestigationFlag,
    ReturnReasonBreakdown,
    ReturnMetricRecord,
    ReturnTimeSeriesPoint,
    ReturnsDataQualityReport,
    ReturnsConfig,
    ReturnsSummary,
    ReturnsIntelligenceResult,
    AnomalySeverity,
    AnomalyDirection,
    AnomalyType,
    ReturnAnomalyConfig,
    ReturnAnomaly,
    ReturnAnomalyResult,
    FeatureDefinition,
    ReturnPredictionRecord,
    ReturnPredictionConfig,
    ReturnPredictionQualityReport,
    TemporalSplitInfo,
)
from commerce_ai.returns.analytics import (
    filter_by_as_of_date,
    assess_returns_data_quality,
    enrich_returns_with_monetary_value,
    compute_reason_breakdowns,
    compute_time_series_points,
    compute_dimensional_metrics,
)
from commerce_ai.returns.service import ReturnsIntelligenceService
from commerce_ai.returns.anomaly import (
    generate_deterministic_anomaly_id,
    generate_anomaly_rationale,
    determine_direction,
    compute_z_score,
    compute_mad_score,
    detect_series_anomaly,
    detect_reason_shift_anomaly,
    ReturnAnomalyService,
)
from commerce_ai.returns.prediction_dataset import (
    FORBIDDEN_LEAKAGE_COLUMNS,
    ReturnPredictionDataset,
    ReturnPredictionDatasetBuilder,
)
from commerce_ai.returns.prediction_models import (
    BaseReturnRiskModel,
    LogisticRegressionReturnModel,
    LightGBMReturnModel,
    verify_feature_matrix_safety,
)
from commerce_ai.returns.prediction_evaluation import (
    compute_classification_metrics,
    evaluate_threshold_scan,
    threshold_analysis_to_dataframe,
    evaluate_segments,
    segments_to_dataframe,
    evaluate_model_pipeline,
)
from commerce_ai.returns.schemas import (
    LogisticRegressionModelConfig,
    LightGBMModelConfig,
    ModelEvaluationMetrics,
    ThresholdAnalysisPoint,
    SegmentEvaluationMetric,
    ReturnPredictionOutputRecord,
    ReturnModelMetadata,
    ReturnRiskBand,
    CalibrationMethod,
    CalibrationBin,
    CalibrationMetrics,
    RiskBandBoundary,
    RiskPolicyConfig,
    ReturnRiskResult,
    RiskBandEvaluation,
    FinancialInputStatus,
    InterventionDecision,
    InterventionRecommendationCode,
    InterventionPolicyConfig,
    ReturnInterventionRecommendation,
    PortfolioInterventionSummary,
)
from commerce_ai.returns.calibration import (
    validate_probability_bounds,
    compute_reliability_curve,
    compute_calibration_metrics,
    ReturnProbabilityCalibrator,
    evaluate_and_compare_calibrations,
)
from commerce_ai.returns.risk import (
    ReturnRiskClassifier,
    evaluate_risk_policy,
    risk_evaluations_to_dataframe,
    evaluate_segment_calibration,
)
from commerce_ai.returns.intervention import (
    AVAILABLE_FINANCIAL_FIELDS,
    UNAVAILABLE_FINANCIAL_FIELDS,
    generate_intervention_id,
    generate_intervention_rationale,
    evaluate_order_line,
    evaluate_order_lines,
    summarize_portfolio,
    portfolio_breakdown_to_dataframe,
    ReturnInterventionService,
)

__all__ = [
    "InvestigationFlag",
    "ReturnReasonBreakdown",
    "ReturnMetricRecord",
    "ReturnTimeSeriesPoint",
    "ReturnsDataQualityReport",
    "ReturnsConfig",
    "ReturnsSummary",
    "ReturnsIntelligenceResult",
    "AnomalySeverity",
    "AnomalyDirection",
    "AnomalyType",
    "ReturnAnomalyConfig",
    "ReturnAnomaly",
    "ReturnAnomalyResult",
    "FeatureDefinition",
    "ReturnPredictionRecord",
    "ReturnPredictionConfig",
    "ReturnPredictionQualityReport",
    "TemporalSplitInfo",
    "filter_by_as_of_date",
    "assess_returns_data_quality",
    "enrich_returns_with_monetary_value",
    "compute_reason_breakdowns",
    "compute_time_series_points",
    "compute_dimensional_metrics",
    "ReturnsIntelligenceService",
    "generate_deterministic_anomaly_id",
    "generate_anomaly_rationale",
    "determine_direction",
    "compute_z_score",
    "compute_mad_score",
    "detect_series_anomaly",
    "detect_reason_shift_anomaly",
    "ReturnAnomalyService",
    "FORBIDDEN_LEAKAGE_COLUMNS",
    "ReturnPredictionDataset",
    "ReturnPredictionDatasetBuilder",
    "LogisticRegressionModelConfig",
    "LightGBMModelConfig",
    "ModelEvaluationMetrics",
    "ThresholdAnalysisPoint",
    "SegmentEvaluationMetric",
    "ReturnPredictionOutputRecord",
    "ReturnModelMetadata",
    "BaseReturnRiskModel",
    "LogisticRegressionReturnModel",
    "LightGBMReturnModel",
    "verify_feature_matrix_safety",
    "compute_classification_metrics",
    "evaluate_threshold_scan",
    "threshold_analysis_to_dataframe",
    "evaluate_segments",
    "segments_to_dataframe",
    "evaluate_model_pipeline",
    "ReturnRiskBand",
    "CalibrationMethod",
    "CalibrationBin",
    "CalibrationMetrics",
    "RiskBandBoundary",
    "RiskPolicyConfig",
    "ReturnRiskResult",
    "RiskBandEvaluation",
    "validate_probability_bounds",
    "compute_reliability_curve",
    "compute_calibration_metrics",
    "ReturnProbabilityCalibrator",
    "evaluate_and_compare_calibrations",
    "ReturnRiskClassifier",
    "evaluate_risk_policy",
    "risk_evaluations_to_dataframe",
    "evaluate_segment_calibration",
    "FinancialInputStatus",
    "InterventionDecision",
    "InterventionRecommendationCode",
    "InterventionPolicyConfig",
    "ReturnInterventionRecommendation",
    "PortfolioInterventionSummary",
    "AVAILABLE_FINANCIAL_FIELDS",
    "UNAVAILABLE_FINANCIAL_FIELDS",
    "generate_intervention_id",
    "generate_intervention_rationale",
    "evaluate_order_line",
    "evaluate_order_lines",
    "summarize_portfolio",
    "portfolio_breakdown_to_dataframe",
    "ReturnInterventionService",
]


