"""Recommendations & Decision Engine (Phase 4B).

Provides deterministic, explainable replenishment recommendations, order quantity sizing,
supply constraints, and draft Purchase Order Proposal generation.
"""

from commerce_ai.recommendations.schemas import (
    UrgencyLevel,
    ReplenishmentConstraint,
    ProposalStatus,
    CostDataStatus,
    ReplenishmentConfig,
    ReplenishmentRecommendation,
    ReplenishmentResult,
    PurchaseOrderLineProposal,
    PurchaseOrderProposal,
    PurchaseOrderProposalResult,
    TransferPriority,
    TransferConstraint,
    WarehouseTransferRecommendation,
    WarehouseRebalancingConfig,
    WarehouseRebalancingResult,
)
from commerce_ai.recommendations.replenishment import (
    determine_urgency,
    generate_deterministic_rationale,
    solve_entity_replenishment,
    ReplenishmentSolver,
)
from commerce_ai.recommendations.purchase_orders import (
    determine_proposal_urgency,
    determine_proposal_expected_delivery_date,
    generate_deterministic_proposal_id,
    generate_proposal_rationale,
    PurchaseOrderProposalService,
)
from commerce_ai.recommendations.warehouse_rebalancing import (
    determine_transfer_priority,
    generate_deterministic_transfer_id,
    generate_transfer_rationale,
    WarehouseRebalancingService,
)

from commerce_ai.recommendations.business_schemas import (
    RecommendationType,
    RecommendationStatus,
    RecommendationPriority,
    RecommendationEvidenceType,
    ConfidenceProvenance,
    ConflictType,
    RecommendationEvidence,
    RecommendationFinancialContext,
    RecommendationOperationalContext,
    RecommendationTraceability,
    RecommendationConflict,
    BusinessRecommendation,
    BusinessRecommendationConfig,
    BusinessRecommendationResult,
)
from commerce_ai.recommendations.business_rules import (
    RecommendationRule,
    RULE_REPLENISHMENT_REVIEW_001,
    RULE_PURCHASE_ORDER_REVIEW_001,
    RULE_WAREHOUSE_REBALANCING_REVIEW_001,
    RULE_SLOW_MOVING_INVENTORY_001,
    RULE_HIGH_VALUE_INVENTORY_001,
    RULE_STOCKOUT_REVIEW_001,
    RULE_RETURN_REVIEW_001,
    RULE_RETURN_ROOT_CAUSE_001,
    RULE_MARGIN_REVIEW_001,
    RULE_FORECAST_REVIEW_001,
    RULE_DATA_QUALITY_REVIEW_001,
    RULE_INVENTORY_REVIEW_001,
    ALL_RULES,
    RULES_BY_ID,
)
from commerce_ai.recommendations.business_recommendations import (
    generate_recommendation_id,
    generate_conflict_id,
    calculate_valid_until,
    RecommendationEvidenceBuilder,
    RecommendationConflictDetector,
    BusinessRecommendationEngine,
)

__all__ = [
    "UrgencyLevel",
    "ReplenishmentConstraint",
    "ProposalStatus",
    "CostDataStatus",
    "ReplenishmentConfig",
    "ReplenishmentRecommendation",
    "ReplenishmentResult",
    "PurchaseOrderLineProposal",
    "PurchaseOrderProposal",
    "PurchaseOrderProposalResult",
    "TransferPriority",
    "TransferConstraint",
    "WarehouseTransferRecommendation",
    "WarehouseRebalancingConfig",
    "WarehouseRebalancingResult",
    "determine_urgency",
    "generate_deterministic_rationale",
    "solve_entity_replenishment",
    "ReplenishmentSolver",
    "determine_proposal_urgency",
    "determine_proposal_expected_delivery_date",
    "generate_deterministic_proposal_id",
    "generate_proposal_rationale",
    "PurchaseOrderProposalService",
    "determine_transfer_priority",
    "generate_deterministic_transfer_id",
    "generate_transfer_rationale",
    "WarehouseRebalancingService",
    # Phase 6G exports
    "RecommendationType",
    "RecommendationStatus",
    "RecommendationPriority",
    "RecommendationEvidenceType",
    "ConfidenceProvenance",
    "ConflictType",
    "RecommendationEvidence",
    "RecommendationFinancialContext",
    "RecommendationOperationalContext",
    "RecommendationTraceability",
    "RecommendationConflict",
    "BusinessRecommendation",
    "BusinessRecommendationConfig",
    "BusinessRecommendationResult",
    "RecommendationRule",
    "RULE_REPLENISHMENT_REVIEW_001",
    "RULE_PURCHASE_ORDER_REVIEW_001",
    "RULE_WAREHOUSE_REBALANCING_REVIEW_001",
    "RULE_SLOW_MOVING_INVENTORY_001",
    "RULE_HIGH_VALUE_INVENTORY_001",
    "RULE_STOCKOUT_REVIEW_001",
    "RULE_RETURN_REVIEW_001",
    "RULE_RETURN_ROOT_CAUSE_001",
    "RULE_MARGIN_REVIEW_001",
    "RULE_FORECAST_REVIEW_001",
    "RULE_DATA_QUALITY_REVIEW_001",
    "RULE_INVENTORY_REVIEW_001",
    "ALL_RULES",
    "RULES_BY_ID",
    "generate_recommendation_id",
    "generate_conflict_id",
    "calculate_valid_until",
    "RecommendationEvidenceBuilder",
    "RecommendationConflictDetector",
    "BusinessRecommendationEngine",
]
